---
title: "Regression Analysis"
author: "Embon,Gerbaudo , Iorio, Barttfeld & Solovey"
date: "8/9/2021"
output: html_document
---

## Levantar datos
                                 
```{r levantar datos, echo=TRUE}

# voy a la carpeta del proyecto
root <- rprojroot::is_rstudio_project
basename(getwd())

# load the function to get the df list
source(root$find_file("Analysis/AuxiliaryFunctions/DataFrame_Filtered.R"))

# get the df list
# experimento = completo,survey,sorteo, todos
DF_list <- DataFrame_Filtered(experimento = "todos", 
                              filtroRT_Disc_Sup = 5000,
                              filtroRT_Disc_Inf = 200,
                              filtroRT_Conf_Sup = 5000,
                              filtroRT_Conf_Inf = 0,
                              filtroTrial = 20,
                              cant_trial_filter = 70)

# DF_list:
# a = df_total
# b = d.sin.normalizar
# c = d.sin.normalizar.mc.filter
# d = d.mc.filter

df_total <- DF_list$a
d.sin.normalizar <- DF_list$b
d.sin.normalizar.mc.filter <- DF_list$c
d.mc.filter <- DF_list$d 
d <- d.mc.filter
###############
### library ###
###############
library(arm)
library(dplyr)

###########################
### Regression Analysis ###
###########################

### lineas para hacer regresion 

d1 = d.sin.normalizar.mc.filter

# sujetos que tienen un 85 % de trials en una misma respuesta de confianza

source(root$find_file("Analysis/AuxiliaryFunctions/discard_by_x_same_confidence.R"))
sujetos_a_descartar <- discard_by_x_same_confidence(85)
d2 <- d1[! d1$sujetos %in% sujetos_a_descartar,]


d <- subset(d, d$sujetos %in% d2$sujetos)

```

##### Empiezo a correr modelos de regresiones

## Modelo 1
```{r modelo 1, echo=TRUE}

vec_variables_values <- list(d$Anhedonia,
                          d$Anxiousness,
                          d$AttentionSeeking,
                          d$Callousness,
                          d$Deceitfulness,
                          d$Depressivity,
                          d$Distractivility,
                          d$Excentricity,
                          d$EmotionalLability,
                          d$Grandiosity,
                          d$Hostility,
                          d$Impulsivity,
                          d$IntimacyAvoidance,
                          d$Irresponsibility,
                          d$Manipulativeness,
                          d$PerceptualDysregulation,
                          d$Perseveration,
                          d$RestrictedAffectivity,
                          d$RigidPerfeccionism,
                          d$RiskTaking,
                          d$SeparationInsecurity,
                          d$Submissiveness,
                          d$Suspiciousness,
                          d$UnusualBeliefsAndExperiences,
                          d$Withdrawal)


vec_variables_string <- c("Anhedonia",
                   "Anxiousness",
                   "AttentionSeeking",
                   "Callousness",
                   "Deceitfulness",
                   "Depressivity",
                   "Distractivility",
                   "Excentricity",
                   "EmotionalLability",
                   "Grandiosity",
                   "Hostility",
                   "Impulsivity",
                   "IntimacyAvoidance",
                   "Irresponsibility",
                   "Manipulativeness",
                   "PerceptualDysregulation",
                   "Perseveration",
                   "RestrictedAffectivity",
                   "RigidPerfeccionism",
                   "RiskTaking",
                   "SeparationInsecurity",
                   "Submissiveness",
                   "Suspiciousness",
                   "UnusualBeliefsAndExperiences",
                   "Withdrawal")

## para cada regresor por separado
######
# for (i in 1:length(vec_variables_string)) {
#   a <- lm(d2$mc ~ vec_variables_values[[i]] + 
#                   d$edad + 
#                   d$Im +
#                   d$edad:vec_variables_values[[i]]) #+
#                   #d$Im: vec_variables_values[[i]])
#   print(vec_variables_string[i])
#   print(summary(a))}

### para todos los regresores juntos

## para todos los regresores juntos
######
# a <- lm(d2$mc ~ vec_variables_values[[1]] + 
#           vec_variables_values[[2]] +
#           vec_variables_values[[3]] + 
#           vec_variables_values[[4]] + 
#           vec_variables_values[[5]] + 
#           vec_variables_values[[6]] + 
#           vec_variables_values[[7]] + 
#           vec_variables_values[[8]] + 
#           vec_variables_values[[9]] + 
#           vec_variables_values[[10]] + 
#           vec_variables_values[[11]] + 
#           vec_variables_values[[12]] + 
#           vec_variables_values[[13]] + 
#           vec_variables_values[[14]] + 
#           vec_variables_values[[15]] + 
#           vec_variables_values[[16]] + 
#           vec_variables_values[[17]] + 
#           vec_variables_values[[18]] + 
#           vec_variables_values[[19]] + 
#           vec_variables_values[[20]] + 
#           vec_variables_values[[21]] + 
#           vec_variables_values[[22]] + 
#           vec_variables_values[[23]] + 
#           vec_variables_values[[24]] + 
#           vec_variables_values[[25]] + 
#           d$edad + 
#           d$Im)


## Para los que nos interesan

## solo los que nos importan
###### 
a <- lm(d2$mc ~ vec_variables_values[[15]] +
          vec_variables_values[[24]] +
          vec_variables_values[[8]] +
          d$edad +
          d$Im)


## muestro los resultados
######
print(vec_variables_string)
print(summary(a))

```
## Modelo 2

```{r Modelo 2, echo=TRUE}

vec_variables_values <- list(d$DomainPsychoticism,
                             d$DomainDisinhibition,
                             d$DomainAntagonism,
                             d$DomainDetachment,
                             d$DomainNegativeAffect)


vec_variables_string <- c("DomainPsychoticism",
                          'DomainDisinhibition',
                          'DomainAntagonism',
                          'DomainDetachment',
                          'DomainNegativeAffect')


# for (i in 1:length(vec_variables_string)) {
#   a <- lm(d2$mc ~ vec_variables_values[[i]] + 
#                   d$edad + 
#                   d$Im +
#                   d$edad:vec_variables_values[[i]]) #+
#                   #d$Im: vec_variables_values[[i]])
#   print(vec_variables_string[i])
#   print(summary(a))
# }


a <- lm(d2$mc ~ vec_variables_values[[1]] +
          vec_variables_values[[2]] +
          vec_variables_values[[3]] +
          vec_variables_values[[4]] +
          vec_variables_values[[5]] +
          d$edad + 
          d$Im) 
print(vec_variables_string)
print(summary(a))
```
