---
title: "Regression Analysis"
author: "Embon,Gerbaudo , Iorio, Barttfeld & Solovey"
date: "8/9/2021"
output: html_document
---

## Levantar datos
                                 
```{r levantar datos, echo=TRUE}

# voy a la carpeta del proyecto
root <- rprojroot::is_rstudio_project
basename(getwd())

####### data frames with filters already applied
filepath <- root$find_file("Data/All_exp_exclusion_criteria/df_total.Rda")
load(file= filepath)

source(root$find_file("Analysis/AuxiliaryFunctions/DataFrame_Filtered_already_applied.R"))
DF_list <- DataFrame_Filtered_already_applied(df_total)

# DF_list:
# a = d (df normalizado)
# b = d.sin.normalizar

d <- DF_list$a
d.sin.normalizar <- DF_list$b

# only male and female genders
d <- d[d$Im == "Femenino" | d$Im == "Masculino",]
d.sin.normalizar <- d.sin.normalizar[d.sin.normalizar$Im == "Femenino" | 
                                       d.sin.normalizar$Im == "Masculino",]

d[d == "Masculino"] <- "1"
d[d == "Femenino"] <- "0"
d$Im <- as.integer(d$Im)

d.sin.normalizar[d.sin.normalizar == "Masculino"] <- "1"
d.sin.normalizar[d.sin.normalizar == "Femenino"] <- "0"
d.sin.normalizar$Im <- as.integer(d.sin.normalizar$Im)

###############
### library ###
###############
library(arm)
library(dplyr)

###########################
### Regression Analysis ###
###########################

### lineas para hacer regresion 

d2 = d.sin.normalizar


```

##### Empiezo a correr modelos de regresiones

## Modelo 1
```{r modelo 1, echo=TRUE}

vec_variables_values <- list(d$Anhedonia,
                          d$Anxiousness,
                          d$AttentionSeeking,
                          d$Callousness,
                          d$Deceitfulness,
                          d$Depressivity,
                          d$Distractivility,
                          d$Excentricity,
                          d$EmotionalLability,
                          d$Grandiosity,
                          d$Hostility,
                          d$Impulsivity,
                          d$IntimacyAvoidance,
                          d$Irresponsibility,
                          d$Manipulativeness,
                          d$PerceptualDysregulation,
                          d$Perseveration,
                          d$RestrictedAffectivity,
                          d$RigidPerfeccionism,
                          d$RiskTaking,
                          d$SeparationInsecurity,
                          d$Submissiveness,
                          d$Suspiciousness,
                          d$UnusualBeliefsAndExperiences,
                          d$Withdrawal)


vec_variables_string <- c("Anhedonia",
                   "Anxiousness",
                   "AttentionSeeking",
                   "Callousness",
                   "Deceitfulness",
                   "Depressivity",
                   "Distractivility",
                   "Excentricity",
                   "EmotionalLability",
                   "Grandiosity",
                   "Hostility",
                   "Impulsivity",
                   "IntimacyAvoidance",
                   "Irresponsibility",
                   "Manipulativeness",
                   "PerceptualDysregulation",
                   "Perseveration",
                   "RestrictedAffectivity",
                   "RigidPerfeccionism",
                   "RiskTaking",
                   "SeparationInsecurity",
                   "Submissiveness",
                   "Suspiciousness",
                   "UnusualBeliefsAndExperiences",
                   "Withdrawal")

## para cada regresor por separado
######
for (i in 1:length(vec_variables_string)) {
  a <- lm(d$m_c ~ vec_variables_values[[i]] +
                  d$edad +
                  d$Im +
                  d$edad:vec_variables_values[[i]]) #+
                  #d$Im: vec_variables_values[[i]])
  print(vec_variables_string[i])
  print(summary(a))}

### para todos los regresores juntos

## para todos los regresores juntos
######
# a <- lm(d2$mc ~ vec_variables_values[[1]] +
#           vec_variables_values[[2]] +
#           vec_variables_values[[3]] +
#           vec_variables_values[[4]] +
#           vec_variables_values[[5]] +
#           vec_variables_values[[6]] +
#           vec_variables_values[[7]] +
#           vec_variables_values[[8]] +
#           vec_variables_values[[9]] +
#           vec_variables_values[[10]] +
#           vec_variables_values[[11]] +
#           vec_variables_values[[12]] +
#           vec_variables_values[[13]] +
#           vec_variables_values[[14]] +
#           vec_variables_values[[15]] +
#           vec_variables_values[[16]] +
#           vec_variables_values[[17]] +
#           vec_variables_values[[18]] +
#           vec_variables_values[[19]] +
#           vec_variables_values[[20]] +
#           vec_variables_values[[21]] +
#           vec_variables_values[[22]] +
#           vec_variables_values[[23]] +
#           vec_variables_values[[24]] +
#           vec_variables_values[[25]] +
#           d$edad +
#           d$Im)


## Para los que nos interesan

## solo los que nos importan
###### 
# a <- lm(d2$mc ~ vec_variables_values[[15]] +
#           vec_variables_values[[24]] +
#           vec_variables_values[[8]] +
#           d$edad +
#           d$Im)


## muestro los resultados
######
# print(vec_variables_string)
# print(summary(a))

```
## Modelo 2

```{r Modelo 2, echo=TRUE}

vec_variables_values <- list(d$DomainPsychoticism,
                             d$DomainDisinhibition,
                             d$DomainAntagonism,
                             d$DomainDetachment,
                             d$DomainNegativeAffect)


vec_variables_string <- c("DomainPsychoticism",
                          'DomainDisinhibition',
                          'DomainAntagonism',
                          'DomainDetachment',
                          'DomainNegativeAffect')


for (i in 1:length(vec_variables_string)) {
  a <- lm(d$m_c ~ vec_variables_values[[i]] +
                  d$edad +
                  d$Im +
                  d$edad:vec_variables_values[[i]]) #+
                  #d$Im: vec_variables_values[[i]])
  print(vec_variables_string[i])
  print(summary(a))
}


# a <- lm(d2$mc ~ vec_variables_values[[1]] +
#           vec_variables_values[[2]] +
#           vec_variables_values[[3]] +
#           vec_variables_values[[4]] +
#           vec_variables_values[[5]] +
#           d$edad +
#           d$Im)
# print(vec_variables_string)
# print(summary(a))
```
